services:
  postgres:
    image: postgres:16
    container_name: postgres_server
    volumes:
      - postgres_data:/var/lib/postgresql/data # Guarda los datos aca
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Crea las tablas automaticamente
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sebas123
      POSTGRES_DB: tasksdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"] # Verifica que postgres esta listo
      interval: 10s
      timeout: 5s
      retries: 5
    
volumes: # Ayuda a guardar los datos de la BD
  postgres_data:
